version: '3.8'

services:
  php-apache:
    image: webdevops/php-apache:8.1
    container_name: basic-php-apache
    ports:
      - "80:80"
    volumes:
      - ./www:/app
    depends_on:
      - mysql
    networks:
      - basic-network
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/app

  mysql:
    image: mysql:8.0
    container_name: basic-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basic_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - basic-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: basic-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - basic-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  basic-network:
    driver: bridge
