version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=xampp
      - MYSQL_DATABASE=xampp
    networks:
      - xampp-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xampp
      MYSQL_DATABASE: xampp
      MYSQL_USER: xampp
      MYSQL_PASSWORD: xampp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - xampp-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: xampp
      MYSQL_ROOT_PASSWORD: xampp
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - xampp-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  xampp-network:
    driver: bridge