version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
      - ./apache/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=xampp
      - MYSQL_DATABASE=xampp
    networks:
      - xampp-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xampp
      MYSQL_DATABASE: xampp
      MYSQL_USER: xampp
      MYSQL_PASSWORD: xampp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - xampp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pxampp"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: xampp
      MYSQL_ROOT_PASSWORD: xampp
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 64M
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xampp-network

volumes:
  mysql_data:
    driver: local

networks:
  xampp-network:
    driver: bridge